language: python
python:
  - "3.5"

cache:
  directories:
    - $HOME/.pip-cache/
# install mdl for checking Markdown
before_install:
  - gem install mdl
notifications:
  email: never

install:
  - pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - pip3 install pytest-flake8
  - pip3 install pytest-cov
  - pip3 install autopep8
  - pip3 install gspread oauth2client
  - pip3 install coveralls

script:
  - pytest gatorgrouper_django/gatorgrouper/tests
  - mdl README.md
  - coverage run --source gatorgrouper_django/gatorgrouper/tests -m py.test 
  - coverage report

after_success:
  coveralls
